# Created 2017-03-01 Wed 15:22
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:nil p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: title:t toc:nil todo:t |:t
#+TITLE: Plotting Time Series of Weather Observations in Emacs
#+DATE: <2017-03-01 Wed>
#+AUTHOR: Julien Chastang
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+SETUPFILE: ../../templates/level-1.org
#+PROPERTY: header-args :exports both

* <2017-03-01 Wed>

[[file:../../static/weatherobs/timeseries.svg]]

** Introduction
<<intro>>

In this post, we will be using Emacs and org-mode to construct a time series of weather observations. If you want the short version of what we will be doing, change the ~station-id~ below and run ~org-babel-execute-buffer~ (~C-c C-v C-b~). For the complete version read on. We will be using the following technologies:
- [[http://orgmode.org][org-mode]]
- [[https://github.com/zweifisch/ob-http][ob-http]], http requests in org Babel
- [[https://www.gnu.org/software/emacs/manual/html_node/org/noweb.html][noweb]] literate programming
- [[http://www.gnuplot.info/][gnuplot]], the venerable plotting utility
- [[https://synopticlabs.org/][Mesowest Synoptic Labs API]]

The org source for this file is located at the source link at the bottom of the page. Indeed, to follow along carefully you will have to view that source link as the HTML rendering has removed some of the org source from this web page.
** Find a Weather Station

Our first job is to find a weather station near our location. We will employ the SynopticLabs Mesonet API to identify a station ID near my current location. I live in Boulder, Colorado at roughly these coordinates: 39.99, -105.22. The Mesonet API has a service to find weather stations nearest a given latitude and longitude point. You have to supply a US ~state~ (easy to forget) and a ~radius~ arguments composed of a latitude, longitude center and a radius distance in miles. In addition, there are a couple of other ancillary arguments including a demo token. Consult the API documentation to ensure you are working within the [[https://synopticlabs.org/api/legal/][terms of use]]. The following URL will provide us a station near by with the help of ob-http:

*** ob-http Request and JSON Response

#+BEGIN_SRC http
  GET http://api.mesowest.net/v2/stations/metadata?state=co&status=active&radius=39.99,-105.22,1&token=demotoken
#+END_SRC

#+RESULTS: 
#+BEGIN_EXAMPLE
{
  "SUMMARY": {
    "METADATA_RESPONSE_TIME": "0.134944915771 ms",
    "RESPONSE_MESSAGE": "OK",
    "RESPONSE_CODE": 1,
    "NUMBER_OF_OBJECTS": 1
  },
  "STATION": [
    {
      "ID": "41017",
      "TIMEZONE": "America\/Denver",
      "LATITUDE": "40.00133",
      "STATE": "CO",
      "LONGITUDE": "-105.23033",
      "STID": "E3608",
      "DISTANCE": 0.96,
      "NAME": "EW3608 Boulder",
      "ELEVATION": "5430",
      "PERIOD_OF_RECORD": {
        "end": "2017-03-01T15:08:00Z",
        "start": "2013-09-25T00:00:00Z"
      },
      "MNET_ID": "65",
      "STATUS": "ACTIVE"
    }
  ]
}
#+END_EXAMPLE


According to this JSON response, there is the "E3608" weather station not far away. We will work with the data from that instrument.

** Timeseries API

Next, we will be using the [[https://synopticlabs.org/api/mesonet/reference/#stationstimeseries][timeseries API]] to retrieve the station data. For example, the following URL retrieves the air temperature from the KDEN station for the last 30 minutes.

#+BEGIN_SRC http
  GET http://api.mesowest.net/v2/stations/timeseries?&stid=kden&recent=30&token=demotoken&vars=air_temp&output=csv
#+END_SRC

#+RESULTS: 
#+BEGIN_EXAMPLE
# STATION: KDEN
# STATION NAME: Denver, Denver International Airport
# LATITUDE: 39.84658
# LONGITUDE: -104.65622
# ELEVATION [ft]: 5404
# STATE: CO
Station_ID,Date_Time,air_temp_set_1
,,Celsius
KDEN,2017-03-01T14:50:00Z,-5.0
KDEN,2017-03-01T14:53:00Z,-5.0
KDEN,2017-03-01T14:55:00Z,-5.0
KDEN,2017-03-01T15:00:00Z,-4.0
KDEN,2017-03-01T15:05:00Z,-3.0
KDEN,2017-03-01T15:10:00Z,-3.0
#+END_EXAMPLE

There are more [[https://synopticlabs.org/api/mesonet/][examples]] of API use as well as the [[https://synopticlabs.org/api/mesonet/reference/#stationstimeseries][API reference]] on SynopticLabs website. 

For the particular example we are shooting for, we will supply the following URL parameters:

- ~stid~, the station ID that we obtained earlier
- ~start~, the start time in UTC (e.g., ~201702171644~)
- ~end~, the end time  in UTC (e.g., ~201702241644~)
- ~units~, the desired units (i.e., metrics or english)
- ~vars~, the [[https://synopticlabs.org/api/mesonet/variables/][sensor variables]]
- ~obtimezone~, the timezone of the response data (i.e., UTC or local)
- ~output~, the output format (e.g., csv)
- ~token~, the request token, in this case guest

** Set up Parameterization With noweb
<<params>>

We will once again be make use of ob-http to retrieve the data, but, this time, we will be employing the Emacs noweb facility to parameterize the ob-http code block. (By the way, "noweb", has always struck me as a terrible name as it seems to imply something about the web browsing, the world wide web, or the Internet, but, in fact, refers to a literate programming style.) Let's start defining our noweb parameters with named org-mode and Emacs Lisp code blocks. We will use the names subsequently via noweb.

*** Start Time

The start time range will be 24 hours ago. Also set the time zone as UTC since that is what the SynopticLabs API requires.

#+NAME: starttime
#+BEGIN_SRC emacs-lisp
  (setenv "TZ" "UTC0")
  (format-time-string "%Y%m%d%H%M" (time-add
                                    (current-time)
                                    (seconds-to-time (- (* 1 24 60 60)))))
#+END_SRC

#+RESULTS: starttime
: 201702281521

*** End Time

The end time will be now.

#+NAME: endtime
#+BEGIN_SRC emacs-lisp
  (format-time-string "%Y%m%d%H%M")
#+END_SRC

#+RESULTS: endtime
: 201703011521

*** Station ID

The station ID we found earlier.

#+NAME: station-id
#+BEGIN_SRC emacs-lisp
  ;; "KBJC"
  "E3608"
  ;; "E7829"
#+END_SRC

#+RESULTS: station-id
: E3608

** Retrieve the Weather Observations
*** Retrieve Data

At this point, we can finally retrieve our data with the help our noweb parameters. For example, ~<<starttime()>>~ will invoke the ~starttime~ code block defined above and insert the result into the http address below. The same is true for ~station-id~ and ~endtime~. See the source link at the bottom to see the noweb parameterization.

#+NAME: timeseries
#+BEGIN_SRC http
  GET http://api.mesowest.net/v2/stations/timeseries?token=demotoken&stid=E3608&start=201702281522&end=201703011522&obtimezone=local&units=metric&vars=air_temp,dew_point_temperature,wind_speed,wind_direction,sea_level_pressure&output=csv
#+END_SRC

*** Post-request cleanup with Emacs Lisp

At this point, we have to write some Emacs Lisp to clean up the response data and make it more org-mode friendly. We will need four helper functions:

- ~take-nth~ is a function to sample data at certain intervals from a list.
- gnuplot does not like empty org-table cells so the ~fix-missing~ function replaces empty cells with the "missing" string.
- The ~find-header~ function locates where the header and actual data are located in the CSV http response.
- The ~clean-header~ function replaces cryptic columns names with ones that are easier to understand.

Armed with these functions, we can clean up our data. Also a note about sampling: large org-tables tend to bog down Emacs so I'm limiting the table size to 30 samples via a Babel header argument, and the ~take-nth~ helper function.

#+NAME: data-table
#+BEGIN_SRC emacs-lisp
  (defun take-nth (n list )
    "Returns a list of every nth item in the list."
    (if (<= n 1) list
      (when list
        (cons (car list)
              (take-nth n (nthcdr n list))))))

  (defun fix-missing (s)
    "Replace missing CSV values with 'missing' to avoid empty cells in org-tables."
    (if (string-match-p ",\s*," s)
        (fix-missing (replace-regexp-in-string ",\s*," ",missing," s))
      s))

  (defun find-header (list)
    "Find row in the CSV data where the column header info starts."
    (when list
      (if (string-prefix-p "Station_ID" (car list) )
          list 
        (find-header (cdr list)))))

  (defun clean-header (header)
    "Provide better names for column headers provided by the API."
    (let ((col-map '(("Station_ID" . "Station")
                      ("Date_Time" . "Date Time")
                      ("altimeter_set_1" . "Altimeter")
                      ("air_temp_set_1" . "Temperature")
                      ("relative_humidity_set_1" . "RH")
                      ("wind_speed_set_1" . "Wind Speed")
                      ("wind_direction_set_1" . "Wind Direction")
                      ("dew_point_temperature_set_1d" . "Dew Point")
                      ("pressure_set_1d" . "Pressure")
                      ("sea_level_pressure_set_1d" . "SLP"))))
      (mapcar (lambda (x) (cdr (assoc x col-map)))
              (split-string header ","))))

  (let* ((string-data (split-string data))
         (rows (find-header string-data))
         (col-hdrs (clean-header (car rows)))
         (units (split-string (cadr rows) ","))
         (d (take-nth (/ (length rows) samples) (cddr rows))))
    (cons col-hdrs
          (cons units
                (cl-loop for s in d
                         collect
                         (let ((row (fix-missing s)))
                           (split-string row ","))))))
#+END_SRC

#+RESULTS: data-table
:RESULTS:
| Station | Date Time                | Altimeter | Temperature |   RH |    Wind Speed | Wind Direction | Dew Point | Pressure |       SLP |
|         |                          |   Pascals |     Celsius |    % | Meters/second |        Degrees |   Celsius |  Pascals |   Pascals |
| E3608   | 2017-02-28T08:23:00-0700 | 101049.79 |         0.0 | 65.0 |           0.9 |          181.0 |     -5.87 | 82725.62 | 101343.89 |
| E3608   | 2017-02-28T09:08:00-0700 | 101015.92 |        1.67 | 55.0 |          1.79 |          128.0 |      -6.5 | 82697.89 | 101187.46 |
| E3608   | 2017-02-28T09:53:00-0700 | 101015.92 |        3.33 | 49.0 |           0.9 |           99.0 |     -6.48 | 82697.89 | 101067.28 |
| E3608   | 2017-02-28T10:38:00-0700 | 101015.92 |        3.89 | 43.0 |          2.23 |           84.0 |     -7.67 | 82697.89 | 101027.13 |
| E3608   | 2017-02-28T11:23:00-0700 | 101015.92 |        3.33 | 45.0 |          1.34 |           92.0 |     -7.59 | 82697.89 | 101067.32 |
| E3608   | 2017-02-28T12:08:00-0700 | 100982.06 |        3.89 | 45.0 |          1.34 |           71.0 |     -7.08 | 82670.17 | 100993.25 |
| E3608   | 2017-02-28T12:53:00-0700 |  100948.2 |        3.89 | 44.0 |          1.79 |           67.0 |     -7.38 | 82642.45 | 100959.39 |
| E3608   | 2017-02-28T13:38:00-0700 | 100982.06 |        3.89 | 43.0 |           0.9 |           32.0 |     -7.67 | 82670.17 | 100993.27 |
| E3608   | 2017-02-28T14:23:00-0700 | 101015.92 |        3.89 | 52.0 |          2.68 |          126.0 |     -5.18 | 82697.89 | 101027.04 |
| E3608   | 2017-02-28T15:08:00-0700 | 101083.65 |        3.33 | 60.0 |          1.79 |           67.0 |     -3.78 | 82753.33 | 101134.93 |
| E3608   | 2017-02-28T15:58:00-0700 | 101252.97 |        2.22 | 63.0 |          0.45 |           98.0 |     -4.18 | 82891.95 | 101384.73 |
| E3608   | 2017-02-28T16:43:00-0700 | 101422.29 |        2.78 | 66.0 |          3.58 |           39.0 |     -3.02 | 83030.57 | 101513.53 |
| E3608   | 2017-02-28T17:28:00-0700 | 101523.88 |        1.11 | 33.0 |          1.79 |          247.0 |    -13.51 | 83113.73 | 101737.56 |
| E3608   | 2017-02-28T18:13:00-0700 | 101659.34 |        0.56 | 29.0 |          2.23 |          269.0 |    -15.57 | 83224.63 | 101913.95 |
| E3608   | 2017-02-28T18:58:00-0700 | 101794.79 |         0.0 | 25.0 |          1.79 |          305.0 |    -17.82 | 83335.52 | 102091.36 |
| E3608   | 2017-02-28T19:43:00-0700 | 101862.52 |       -1.11 | 30.0 |           0.9 |          338.0 |    -16.62 | 83390.97 | 102242.27 |
| E3608   | 2017-02-28T20:33:00-0700 | 101930.25 |       -1.11 | 28.0 |          1.34 |          309.0 |    -17.44 | 83446.41 | 102310.26 |
| E3608   | 2017-02-28T21:18:00-0700 | 101997.98 |       -1.11 | 29.0 |           0.9 |          280.0 |    -17.02 | 83501.86 | 102378.24 |
| E3608   | 2017-02-28T22:03:00-0700 | 102031.84 |       -2.22 | 32.0 |          0.45 |           15.0 |    -16.82 | 83529.58 |  102496.1 |
| E3608   | 2017-02-28T22:48:00-0700 | 102031.84 |       -1.67 | 32.0 |          0.45 |            5.0 |    -16.34 | 83529.58 | 102454.44 |
| E3608   | 2017-02-28T23:33:00-0700 |  102065.7 |       -1.67 | 30.0 |          2.23 |          267.0 |    -17.11 |  83557.3 | 102488.45 |
| E3608   | 2017-03-01T00:18:00-0700 | 102099.57 |       -1.11 | 29.0 |           0.9 |          287.0 |    -17.02 | 83585.03 | 102480.21 |
| E3608   | 2017-03-01T01:03:00-0700 | 102133.43 |       -1.11 | 29.0 |          1.79 |          304.0 |    -17.02 | 83612.75 |  102514.2 |
| E3608   | 2017-03-01T01:48:00-0700 |  102167.3 |       -1.11 | 30.0 |           0.9 |          250.0 |    -16.62 | 83640.48 | 102548.19 |
| E3608   | 2017-03-01T02:33:00-0700 | 102133.43 |       -1.67 | 32.0 |           0.9 |           36.0 |    -16.34 | 83612.75 | 102556.45 |
| E3608   | 2017-03-01T03:18:00-0700 | 102133.43 |       -1.67 | 32.0 |           0.9 |           89.0 |    -16.34 | 83612.75 | 102556.45 |
| E3608   | 2017-03-01T04:03:00-0700 |  102167.3 |       -2.22 | 33.0 |          2.23 |          102.0 |    -16.46 | 83640.48 | 102632.18 |
| E3608   | 2017-03-01T04:53:00-0700 | 102268.89 |       -3.33 | 37.0 |          0.45 |          340.0 |    -16.07 | 83723.65 | 102819.05 |
| E3608   | 2017-03-01T05:38:00-0700 | 102302.75 |       -3.33 | 39.0 |          0.45 |           95.0 |    -15.43 | 83751.37 | 102853.08 |
| E3608   | 2017-03-01T06:23:00-0700 | 102336.62 |        -5.0 | 46.0 |           0.0 |        missing |    -14.94 | 83779.09 | 103016.24 |
| E3608   | 2017-03-01T07:08:00-0700 | 102472.07 |        -5.0 | 48.0 |           0.0 |        missing |    -14.42 | 83889.98 | 103152.58 |
| E3608   | 2017-03-01T07:53:00-0700 |  102539.8 |       -1.67 | 36.0 |          0.45 |          355.0 |    -14.92 | 83945.43 | 102964.48 |
:END:

** Timeseries with Gnuplot
*** Gnuplot

At this point, we are ready to plot our data table with gnuplot. The following code took bit of experimentation to get right as well as studying the [[http://gnuplot.sourceforge.net/documentation.html][gnuplot official documentation]]. But essentially we are plotting in one stacked plot,

- Sea level pressure
- Temperature and dew point
- Relative humidity
- Wind speed
- Wind direction

One tricky part is I had to alternate the Y-axis labeling so that the successive plot labels would not run into one another.

#+BEGIN_SRC gnuplot
  reset

  set terminal svg size 800, 800 enhanced truecolor font 'Verdana,13'

  set multiplot layout 5,1 rowsfirst

  set grid
  set lmargin 12
  set rmargin 8

  set style line 1 lc rgb '#000000' lt 1 lw 2 pt 9 ps 1.0
  set style line 2 lc rgb '#dd181f' lt 1 lw 2 pt 7 ps 1.0
  set style line 3 lc rgb '#0060ad' lt 1 lw 2 pt 7 ps 0.75
  set style line 4 lc rgb '#00ff00' lt 1 lw 2 pt 7 ps 1
  set style line 5 lc rgb '#00ff00' lt 1 lw 2 pt 5 ps 0.75

  set title "Weather for E3608"

  set xdata time
  set timefmt "%Y-%m-%dT%H:%M:%SZ"
  set format x " " 

  set yrange [:*]
  set ylabel "Pascals" offset 0

  set bmargin 0
  set offsets graph 0, 0, 500, 10

  set size 1,0.24
  set origin 0.0,0.76

  plot data using " Date Time":"SLP" with linespoints ls 1 title 'Sea Level Pressure'

  set title " "

  set yrange [:*]
  set ytics offset 80,0
  set ylabel "Celsius" offset 88

  set tmargin 0
  set offsets graph 0, 0, 10, 1

  set size 1,0.17
  set origin 0.0,0.59

  plot data using "Date Time":"Temperature" with linespoints ls 2 title 'Temperature',\
       data using "Date Time":"Dew Point" with linespoints ls 3 title 'Dewpoint'

  set yrange [0:100]
  set ytics offset 0,0
  set ylabel "%" offset 0

  set offsets graph 0, 0, 0, 0 

  set size 1,0.17
  set origin 0.0,0.42

  plot data using "Date Time":"RH" with linespoints ls 4 title 'RH'

  set yrange [0:*]
  set ytics offset 80,0
  set ylabel "Meters per Second" offset 88

  set offsets graph 0, 0, 1, 0

  set size 1,0.17
  set origin 0.0,0.25

  plot data using " Date Time":"Wind Speed" with linespoints ls 5 title 'Wind Speed'

  set xtics rotate by -45
  set format x "%m/%d %Hh"

  set yrange [0:360]
  set ylabel "Direction" offset 0
  set ytics ("N" 0,"NE" 45,"E" 90 ,"SE" 135, "S" 180, "SW" 225, "W" 270, "NW" 315) offset 0,0

  set bmargin 4

  set size 1,0.25
  set origin 0.0,0

  plot data using " Date Time":"Wind Direction" pt 3 ps 1.0 title 'Wind Direction'

  unset multiplot
#+END_SRC

#+RESULTS: 
[[file:../../static/weatherobs/timeseries.svg]]

** Babel

As mentioned in the [[intro][introduction]], to generate the data table and plot, this entire buffer can be run in literate programming fashion with ~org-babel-execute-buffer~ (~C-c C-v C-b~). You can parameterize the start and end time, and the station ID via [[params][noweb parameters]]. I will leave it as an exercise to the reader to supply additional parameterization for the station variables, for example.

** Ideas for Improvements

In the future, I would like to incorporate more information in the plot. Specifically,

- Replace the wind and direction time series with wind barbs.
- [[http://www.wpc.ncep.noaa.gov/html/stationplot.shtml][Station plot weather symbols]]
- Add precipitation data

I'll have to learn more about gnuplot in order to achieve the first two bullet items.
